Repository Leets-Official/SEEAT-FE, pull requests merged in 2025-07, with the labels that each got.

#2 [Chore] 프로젝트 초기 세팅
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  .gitignore
  .prettierrc
  eslint.config.js
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/api/api.ts
  src/assets/index.tsx
  src/assets/react.svg
  src/components/index.tsx
  src/global.css
  src/index.css
  src/main.tsx
  src/pages/home/index.tsx
  src/pages/my/index.tsx
  src/pages/signup/index.tsx
  src/routes/route.tsx
  src/types/svg.d.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 🔧Chore

#14 [feat] input,textarea +header 공통컴포넌트 구현
  package-lock.json
  package.json
  src/assets/icons/bookmark_f.svg
  src/assets/icons/bookmark_o.svg
  src/assets/icons/chevron.svg
  src/assets/icons/heart_f.svg
  src/assets/icons/heart_o.svg
  src/assets/icons/icon_gear.svg
  src/assets/icons/plus.svg
  src/assets/index.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/HomeHeader.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Textarea/Textarea.tsx
  src/components/examples/HeaderExamples.tsx
  src/components/examples/InputExamples.tsx
  src/components/examples/TextareaExamples.tsx
  src/routes/route.tsx
Labels: 🎨Style, ✨Feature

#17 [Style] 전역 스타일 수정
  src/App.tsx
  src/components/common/Button/Button.styled.ts
  src/components/common/Button/Button.tsx
  src/components/examples/ImageExamples.tsx
  src/global.css
  src/pages/signup/LoginPage.tsx
  src/routes/route.tsx
Labels: 🎨Style

#23 [Feat] 후기 작성 플로우 구현
  package.json
  src/App.tsx
  src/assets/icons/star_fill.svg
  src/assets/icons/star_half.svg
  src/assets/icons/star_line.svg
  src/assets/index.tsx
  src/components/common/Header/Header.tsx
  src/components/common/ImagePreview/ImagePreviewItem.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Textarea/Textarea.tsx
  src/components/index.tsx
  src/components/review/ReviewLayout.tsx
  src/components/review/TagSection.tsx
  src/constants/cinema.ts
  src/constants/index.ts
  src/constants/reviewTags.ts
  src/global.css
  src/hooks/index.tsx
  src/hooks/useImageUpload.ts
  src/pages/onboarding/OnboardingGenrePage.tsx
  src/pages/review/CinemaSelect.tsx
  src/pages/review/MovieInfoStep.tsx
  src/pages/review/RatingStep.tsx
  src/pages/review/ReviewContent.tsx
  src/pages/review/TagPage.tsx
  src/pages/review/TicketPage.tsx
  src/routes/route.tsx
  src/store/index.tsx
  src/store/useReviewStore.ts
  src/utils/rating.ts
Labels: 🎨Style, ✨Feature

#25 [Feat]회원가입 온보딩 페이지 구현
  src/assets/icons/kakao_icon.svg
  src/assets/icons/naver_icon.svg
  src/assets/icons/seeat_logo.svg
  src/components/common/ProgressBar/ProgressBar.tsx
  src/components/common/ToggleTab/ToggleTab.tsx
  src/components/common/ToggleTab/ToggleTab.types.ts
  src/components/index.tsx
  src/pages/onboarding/OnboardingGenrePage.tsx
  src/pages/onboarding/OnboardingNicknamePage.tsx
  src/pages/onboarding/OnboardingTheaterPage.tsx
  src/pages/review/CinemaSelect.tsx
  src/pages/signup/LoginPage.tsx
  src/pages/splash/SplashPage.tsx
  src/routes/route.tsx
  src/store/useOnboardingStore.ts
  src/types/onboarding.ts
Labels: 🎨Style, ✨Feature

#28 [Feat] API 인스턴스 작성
  package-lock.json
  package.json
  src/api/api.ts
  src/types/api-response.ts
Labels: 🔗API, ✨Feature

#33 [feat] 마이, 후기검색 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/__mocks/mockReviews.ts
  src/assets/icons/check_square_off.svg
  src/assets/icons/check_square_on.svg
  src/assets/icons/chevron_down.svg
  src/assets/icons/chevron_right.svg
  src/assets/icons/chevron_up.svg
  src/assets/icons/filter.svg
  src/assets/icons/level1.svg
  src/assets/icons/level2.svg
  src/assets/icons/level3.svg
  src/assets/icons/level4.svg
  src/assets/icons/logo.svg
  src/assets/icons/more_vertical.svg
  src/assets/icons/my_profile.svg
  src/assets/icons/my_profile_edit.svg
  src/assets/icons/pencil.svg
  src/assets/icons/search.svg
  src/assets/index.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/HeaderBasic.tsx
  src/components/common/Header/HomeHeader.tsx
  src/components/common/Input/Input.tsx
  src/components/common/LevelCard/LeveCard.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/Modal.types.ts
  src/components/common/ReviewFilter/AccordionSection.tsx
  src/components/common/ReviewFilter/FilterCheckbox.tsx
  src/components/common/SearchInput/SearchInput.tsx
  src/components/common/Textarea/Textarea.tsx
  src/components/examples/HeaderExamples.tsx
  src/components/examples/InputExamples.tsx
  src/components/index.tsx
  src/constants/level.ts
  src/contexts/FilterContext.tsx
  src/contexts/useFilter.ts
  src/global.css
  src/main.tsx
  src/pages/my/CinemaChoice.tsx
  src/pages/my/MyBookmark.tsx
  src/pages/my/MyFeedback.tsx
  src/pages/my/MyPage.tsx
  src/pages/my/MyReview.tsx
  src/pages/my/MySetting.tsx
  src/pages/my/ProfileEdit.tsx
  src/pages/my/SelectGenre.tsx
  src/pages/my/index.tsx
  src/pages/search/ReviewFilter.tsx
  src/pages/search/ReviewSearch.tsx
  src/pages/search/ReviewSearchResult.tsx
  src/routes/route.tsx
  src/store/modalStore.ts
  src/types/onboarding.ts
  src/vite-env.d.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🙋🏻‍♀️Question, ✨Feature
